import streamlit as st
import pandas as pd
import numpy as np
import time
st.title("Akshays Kitchen And Cakes(Title)")
st.header("Akshays Kitchen And Cakes(Header)")
st.subheader("Akshays Kitchen And Cakes(Sub-header)")
st.write("Akshays Kitchen And Cakes(Text)")
st.markdown("Akshays Kitchen And Cakes(Markdown)")
st.caption("Akshays Kitchen And Cakes(Caption)")
st.image("/Users/Akshay/Pictures/xyz.png")
st.checkbox("checkbox")
st.button("click Button")
st.radio("pick your city",["pune","mumbai","delhi","surat"])
st.selectbox("pick your city",["pune","mumbai","delhi","surat"])
st.multiselect("pick favourite sports",["cricket","football","basketball"])
st.select_slider("Give a Remark",["Bad","Good","Excellent"])
st.slider("Your Marks",0,100)
on=st.toggle("Activate Feature")
if on:
    st.write("Feature Activated!")
number=st.number_input("Insert A Number")
st.write("The Current Number Is",number)
d=st.date_input("When's Your Birthday",value=None)
st.write("Your Birthday Is",d)
t=st.time_input("Set An Alarm For",value=None)
st.write("Alarm Is Set For",t)
st.number_input("Enter Your Marks",0,100)
st.text_input("Enter Text")
st.date_input("Exam Date")
st.time_input("Exam Time")
st.text_area("Description")
st.file_uploader("Upload File")
st.color_picker("Choose a Color")
st.success("Success")
st.error("Error")
st.warning("Warning")
st.info("Information")
st.exception(RuntimeError("RuntimeError exception"))
st.sidebar.title("Akshay's Kitchen And Cakes")
st.sidebar.image("/Users/Akshay/Pictures/xyz.png")
df=pd.DataFrame(np.random.randn(50,20),columns=("col %d" % i for i in range(20)))
st.dataframe(df)
df=pd.DataFrame(np.random.randn(10,5),columns=("col %d" % i for i in range(5)))
st.table(df)
col1,col2,col3=st.columns(3)
col1.metric("Temperature","70°F","1.2°F")
col2.metric("Wind","9 mph","-8%")
col3.metric("Humidity","86%","4%")
prompt=st.chat_input("Say Something")
if prompt:
    st.write(f"user has sent the following prompt:(prompt)")

with st.status("step 1"):
    st.write("step 2")
    time.sleep(1)
    st.write("step 3")
    time.sleep(1)
    st.write("step 4")
    time.sleep(1)
st.button("Rerun")
chart_data=pd.DataFrame(np.random.randn(20,3),columns=["a","b","c"])
st.area_chart(chart_data)
chart_data=pd.DataFrame(np.random.randn(20,3),columns=["a","b","c"])
st.bar_chart(chart_data)
chart_data=pd.DataFrame(np.random.randn(20,3),columns=["a","b","c"])
st.line_chart(chart_data)
df=pd.DataFrame({"lat":[19.979212],"lon":[73.754131]})
st.map(df)
chart_data=pd.DataFrame(np.random.randn(20,3),columns=["a","b","c"])
st.scatter_chart(chart_data)
with st.chat_message("user"):
    st.write("Hello Ji")
    